import PageMetaData from '@/components/PageTitle'
import { apiFetch } from '@/helpers/api'
import { FormEvent, useEffect, useState } from 'react'
import { Alert, Badge, Button, Card, CardBody, Form, Table } from 'react-bootstrap'

type Advance = { _id: string; amount: number; deductedAmount: number; reason: string; status: string; createdAt: string; deductionSchedule: { monthlyAmount: number } }

const MyAdvancesPage = () => {
  const [advances, setAdvances] = useState<Advance[]>([]); const [form, setForm] = useState({ amount: '', reason: '', monthlyAmount: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => apiFetch<{ data: Advance[] }>('/hr/advances').then((response) => setAdvances(response.data)).catch((value) => setError(value instanceof Error ? value.message : 'Unable to load salary advances'))
  useEffect(() => { load() }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await apiFetch('/hr/advances', { method: 'POST', body: JSON.stringify({ amount: Number(form.amount), reason: form.reason, deductionSchedule: { monthlyAmount: Number(form.monthlyAmount) } }) }); setForm({ amount: '', reason: '', monthlyAmount: '' }); load() } catch (value) { setError(value instanceof Error ? value.message : 'Unable to submit salary advance request') } finally { setSaving(false) } }
  return <><PageMetaData title="Salary Advance" /><Card className="mb-3"><CardBody><h4 className="card-title mb-1">Request salary advance</h4><p className="text-muted">Approved amounts are deducted from future monthly payroll at the amount you request.</p>{error && <Alert variant="danger">{error}</Alert>}<Form className="row g-3" onSubmit={submit}><div className="col-md-3"><Form.Label>Advance amount</Form.Label><Form.Control required min="0.01" step="0.01" type="number" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></div><div className="col-md-3"><Form.Label>Monthly deduction</Form.Label><Form.Control required min="0.01" step="0.01" type="number" value={form.monthlyAmount} onChange={(event) => setForm({ ...form, monthlyAmount: event.target.value })} /></div><div className="col-md-4"><Form.Label>Reason</Form.Label><Form.Control required value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></div><div className="col-md-2 d-flex align-items-end"><Button type="submit" className="w-100" disabled={saving}>{saving ? 'Submitting…' : 'Submit request'}</Button></div></Form></CardBody></Card><Card><CardBody><h4 className="card-title mb-3">My requests</h4><Table responsive><thead><tr><th>Amount</th><th>Monthly deduction</th><th>Deducted</th><th>Reason</th><th>Status</th><th>Requested</th></tr></thead><tbody>{advances.map((advance) => <tr key={advance._id}><td>{advance.amount}</td><td>{advance.deductionSchedule.monthlyAmount}</td><td>{advance.deductedAmount}</td><td>{advance.reason}</td><td><Badge bg={advance.status === 'approved' ? 'success' : advance.status === 'rejected' ? 'danger' : advance.status === 'settled' ? 'secondary' : 'warning'}>{advance.status}</Badge></td><td>{new Date(advance.createdAt).toLocaleDateString()}</td></tr>)}{!advances.length && <tr><td colSpan={6} className="text-center text-muted py-4">No salary advance requests yet.</td></tr>}</tbody></Table></CardBody></Card></>
}

export default MyAdvancesPage
