services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./backend/.env.production
    ports:
      - "4000:4000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5173:8080"
    depends_on:
      - backend
    restart: unless-stopped
