import { Router } from 'express';
import { asyncHandler } from '../../middleware/async-handler.js';
import { authenticate, authorizeAppModule, authorizeInventoryModule } from '../auth/middleware/auth.middleware.js';
import { multipartUpload } from '../../middleware/upload.middleware.js';
import { uploadFiles } from '../../controllers/upload.controller.js';
import { rateLimit } from '../../middleware/rate-limit.middleware.js';
import * as controller from './controllers/inventory.controller.js';
export const inventoryRouter = Router();
inventoryRouter.use(asyncHandler(authenticate), authorizeAppModule('inventory'));
inventoryRouter.get('/categories', authorizeInventoryModule('categories'), asyncHandler(controller.listCategories));
inventoryRouter.post('/categories', authorizeInventoryModule('categories', 'manage'), asyncHandler(controller.createCategory));
inventoryRouter.patch('/categories/:id', authorizeInventoryModule('categories', 'manage'), asyncHandler(controller.updateCategory));
inventoryRouter.delete('/categories/:id', authorizeInventoryModule('categories', 'manage'), asyncHandler(controller.deleteCategory));
inventoryRouter.get('/reports/low-stock', authorizeInventoryModule('reports'), asyncHandler(controller.lowStockReport));
inventoryRouter.get('/purchases', authorizeInventoryModule('transactions'), asyncHandler(controller.listPurchases));
inventoryRouter.get('/item-categories', authorizeInventoryModule('items'), asyncHandler(controller.listCategories));
inventoryRouter.get('/suppliers', authorizeInventoryModule('items'), asyncHandler(controller.listSuppliers));
inventoryRouter.post('/suppliers', authorizeInventoryModule('items', 'manage'), asyncHandler(controller.createSupplier));
inventoryRouter.patch('/suppliers/:id', authorizeInventoryModule('items', 'manage'), asyncHandler(controller.updateSupplier));
inventoryRouter.post('/uploads', authorizeInventoryModule('items', 'manage'), asyncHandler(rateLimit({ scope: 'inventory-upload', limit: 10, windowMs: 15 * 60 * 1000 })), multipartUpload, asyncHandler(uploadFiles));
inventoryRouter.get('/items', authorizeInventoryModule('items'), asyncHandler(controller.listItems));
inventoryRouter.post('/items', authorizeInventoryModule('items', 'manage'), asyncHandler(controller.createItem));
inventoryRouter.get('/items/:id', authorizeInventoryModule('items'), asyncHandler(controller.getItem));
inventoryRouter.patch('/items/:id', authorizeInventoryModule('items', 'manage'), asyncHandler(controller.updateItem));
inventoryRouter.delete('/items/:id', authorizeInventoryModule('items', 'manage'), asyncHandler(controller.deleteItem));
inventoryRouter.get('/items/:id/transactions', authorizeInventoryModule('transactions'), asyncHandler(controller.listTransactions));
inventoryRouter.post('/items/:id/transactions', authorizeInventoryModule('transactions', 'manage'), asyncHandler(controller.createTransaction));
