import PageMetaData from '@/components/PageTitle'
import { apiFetch } from '@/helpers/api'
import { useEffect, useState } from 'react'
import { Alert, Badge, Button, Card, CardBody, Table } from 'react-bootstrap'

type Claim = { _id: string; category: string; amount: number; note: string; employee: { user: { name: string; email: string } }; receipts: { key: string; url?: string; originalName?: string }[]; createdAt: string }
const ExpenseApprovalsPage = () => {
  const [claims, setClaims] = useState<Claim[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState('')
  const load = () => apiFetch<{ data: Claim[] }>('/hr/expenses?status=pending').then((response) => setClaims(response.data)).catch((value) => setError(value instanceof Error ? value.message : 'Unable to load claims'))
  useEffect(() => { load() }, [])
  const decide = async (id: string, status: 'approved' | 'rejected') => { if (!window.confirm(`${status === 'approved' ? 'Approve' : 'Decline'} this reimbursement?`)) return; setSaving(id); try { await apiFetch(`/hr/expenses/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load() } catch (value) { setError(value instanceof Error ? value.message : 'Unable to update claim') } finally { setSaving('') } }
  return <><PageMetaData title="Expense approvals" /><Card><CardBody><div className="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h4 className="card-title mb-1">Reimbursement approvals</h4><p className="text-muted mb-0">Approved claims are added to the employee’s next payroll reimbursement. Declined claims are never included.</p></div><Badge bg="warning" text="dark">{claims.length} pending</Badge></div>{error && <Alert variant="danger">{error}</Alert>}<Table responsive className="align-middle mb-0"><thead><tr><th>Employee</th><th>Category</th><th>Amount</th><th>Payment note</th><th>Screenshot</th><th>Submitted</th><th className="text-end">Decision</th></tr></thead><tbody>{claims.map((claim) => <tr key={claim._id}><td><div className="fw-medium">{claim.employee?.user?.name}</div><small className="text-muted">{claim.employee?.user?.email}</small></td><td>{claim.category}</td><td>{claim.amount}</td><td>{claim.note}</td><td>{claim.receipts.map((receipt) => <a className="d-block" key={receipt.key} href={receipt.url} target="_blank" rel="noreferrer">{receipt.originalName || 'Payment screenshot'}</a>)}</td><td>{new Date(claim.createdAt).toLocaleDateString()}</td><td className="text-end text-nowrap"><Button size="sm" className="me-2" disabled={Boolean(saving)} onClick={() => decide(claim._id, 'approved')}>{saving === claim._id ? 'Saving…' : 'Approve'}</Button><Button size="sm" variant="outline-danger" disabled={Boolean(saving)} onClick={() => decide(claim._id, 'rejected')}>Decline</Button></td></tr>)}{!claims.length && <tr><td colSpan={7} className="text-center text-muted py-4">No reimbursement requests are waiting for approval.</td></tr>}</tbody></Table></CardBody></Card></>
}
export default ExpenseApprovalsPage
