import { renderPdf } from '../../../services/pdf.service.js';

const escape = (value) => String(value ?? '-').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
const money = (value) => Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function createChallanPdf(challan) {
  const client = challan.client; const items = challan.lineItems.map((item, index) => `<tr><td>${index + 1}</td><td>${escape(item.description)}</td><td>${escape(item.hsnCode)}</td><td class="right">${item.quantity}</td><td>${escape(item.unit)}</td><td class="right">${money(item.rate)}</td><td class="right">${money(item.amount)}</td></tr>`).join('');
  return renderPdf(`<!doctype html><html><head><style>@page{size:A4;margin:12mm}body{font:11px Arial;color:#000}h1,h2,p{margin:0}.top,.meta,.items,.summary,.footer{width:100%;border-collapse:collapse}.top td{font-weight:bold;border-bottom:1px solid;padding:6px}.center{text-align:center}.right{text-align:right}.meta td,.items td,.items th,.summary td,.footer td{border:1px solid;padding:6px;vertical-align:top}.items th{font-weight:bold}.company{text-align:center;padding:12px;border-bottom:1px solid}.receiver{display:flex;border:1px solid}.receiver>div{width:50%;padding:8px}.receiver>div+div{border-left:1px solid}.summary{margin-top:0}.terms{margin-top:15px}.sign{text-align:right;margin-top:40px;font-weight:bold}</style></head><body><table class="top"><tr><td>GSTIN: 06ABXFA0801H1ZK</td><td class="center">DELIVERY CHALLAN</td><td class="right">ORIGINAL COPY</td></tr></table><div class="company"><h1>ABSTERAS</h1><p>PLOT NO -A-1140 SUSHANT LOK-1, GURUGRAM, HARYANA</p><p>E-MAIL: design.absteras@gmail.com · MOB: +91-9838034555</p></div><div class="receiver"><div><b>Details of Receiver</b><br><br><b>NAME:</b> ${escape(client.name)}<br><b>ADDRESS:</b> ${escape(client.shippingAddress || client.billingAddress)}<br>STATE: ${escape(client.state)}<br>STATE CODE: ${escape(client.stateCode)}<br>PHONE NO.: ${escape(client.phone)}<br>GSTIN: ${escape(client.gstin)}</div><div><b>CHALLAN NO: ${escape(challan.challanNumber)}</b><br><br>DATE: ${new Date(challan.challanDate).toLocaleDateString('en-GB')}<br><br><b>TRANSPORT TYPE:</b> ${escape(challan.transportType)}<br><b>VEHICLE NO.:</b> ${escape(challan.vehicleNumber)}<br><b>E-WAY BILL NO.:</b> ${escape(challan.eWayBillNumber)}</div></div><table class="items"><thead><tr><th>S NO.</th><th>Descriptions of Goods</th><th>HSN Code</th><th>QTY.</th><th>Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${items}</tbody><tfoot><tr><th colspan="3" class="right">TOTAL</th><th class="right">${challan.lineItems.reduce((sum, item) => sum + item.quantity, 0)}</th><th colspan="2"></th><th class="right">${money(challan.taxableAmount)}</th></tr></tfoot></table><table class="summary"><tr><td rowspan="4"><b>Total Amount: ${money(challan.totalAmount)}</b></td><td><b>Freight Charge</b></td><td class="right">${money(challan.freightCharge)}</td></tr><tr><td><b>Goods Assessable Value</b></td><td class="right">${money(challan.taxableAmount)}</td></tr><tr><td><b>GST</b></td><td class="right">${money(challan.gstAmount)}</td></tr><tr><td><b>Round Off</b></td><td class="right">${money(challan.roundOff)}</td></tr><tr><td></td><td><b>TOTAL AMOUNT</b></td><td class="right"><b>${money(challan.totalAmount)}</b></td></tr></table><div class="terms"><b>TERMS AND CONDITIONS</b><br>Goods once sold are not refundable. Interest will be charged at 2% per month if payment is not made within 30 days. All disputes are subject to G.B. Nagar jurisdiction only.</div><div class="sign">ABSTERAS<br><br>Authorised Signatory</div></body></html>`);
}
