import { Router } from 'express';
import { createHoliday, deleteHoliday, listAttendance, listHolidays, markAttendance, updateHoliday } from '../controllers/attendance.controller.js';
import { createLeaveRequest, createLeaveType, creditCompOff, decideLeaveRequest, deleteLeaveType, encashLeave, listLeaveBalances, listLeaveRequests, listLeaveTypes, updateLeaveType } from '../controllers/leave.controller.js';
import { createExpenseClaim, decideExpenseClaim, listExpenseClaims } from '../controllers/expense.controller.js';
import { attendanceLeaveReport, headcountAttritionReport, payrollCostReport } from '../controllers/hr-report.controller.js';
import { employeeMonthlyOverview } from '../controllers/employee-overview.controller.js';
import { hrDashboard } from '../controllers/hr-dashboard.controller.js';
import { createAdvance, createPayrollRun, createSalaryStructure, decideAdvance, downloadBankFile, getPayrollRun, listAdvances, listMyAdvances, listPayrollRuns, listSalaryStructures, previewPayroll, previewSettlement, processPayrollRun, requestAdvance, updateSalaryStructure } from '../controllers/payroll.controller.js';
import { createDepartment, createDesignation, createEmployee, deleteDepartment, deleteDesignation, deleteEmployee, getEmployee, listDepartments, listDesignations, listEmployees, updateDepartment, updateDesignation, updateEmployee } from '../controllers/hr.controller.js';
import { asyncHandler } from '../middleware/async-handler.js';
import { authenticate, authorizeHrModule, authorizeRoles } from '../middleware/auth.middleware.js';

export const hrRouter = Router();
hrRouter.use(asyncHandler(authenticate));

hrRouter.get('/dashboard', authorizeHrModule('employees', 'manage'), asyncHandler(hrDashboard));

for (const [path, list, create, update, remove] of [['/departments', listDepartments, createDepartment, updateDepartment, deleteDepartment], ['/designations', listDesignations, createDesignation, updateDesignation, deleteDesignation]]) {
  hrRouter.get(path, authorizeHrModule('employees', 'view'), asyncHandler(list));
  hrRouter.post(path, authorizeRoles('superadmin', 'admin'), asyncHandler(create));
  hrRouter.patch(`${path}/:id`, authorizeRoles('superadmin', 'admin'), asyncHandler(update));
  hrRouter.delete(`${path}/:id`, authorizeRoles('superadmin', 'admin'), asyncHandler(remove));
}
hrRouter.get('/employees', authorizeHrModule('employees', 'view'), asyncHandler(listEmployees));
hrRouter.get('/employee-overview', authorizeHrModule('employee-overview', 'view'), asyncHandler(employeeMonthlyOverview));
hrRouter.post('/employees', authorizeHrModule('employees', 'manage'), asyncHandler(createEmployee));
hrRouter.get('/employees/:id', authorizeHrModule('employees', 'view'), asyncHandler(getEmployee));
hrRouter.patch('/employees/:id', authorizeHrModule('employees', 'manage'), asyncHandler(updateEmployee));
hrRouter.delete('/employees/:id', authorizeHrModule('employees', 'manage'), asyncHandler(deleteEmployee));
hrRouter.get('/attendance', authorizeHrModule('attendance', 'view'), asyncHandler(listAttendance));
hrRouter.get('/attendance/employees', authorizeHrModule('attendance', 'manage'), asyncHandler(listEmployees));
hrRouter.post('/attendance', authorizeHrModule('attendance', 'manage'), asyncHandler(markAttendance));
hrRouter.get('/holidays', authorizeHrModule('attendance', 'view'), asyncHandler(listHolidays));
hrRouter.post('/holidays', authorizeHrModule('attendance', 'manage'), asyncHandler(createHoliday));
hrRouter.patch('/holidays/:id', authorizeHrModule('attendance', 'manage'), asyncHandler(updateHoliday));
hrRouter.delete('/holidays/:id', authorizeHrModule('attendance', 'manage'), asyncHandler(deleteHoliday));
hrRouter.get('/leave/types', authorizeHrModule('leave', 'view'), asyncHandler(listLeaveTypes));
hrRouter.post('/leave/types', authorizeHrModule('leave', 'manage'), asyncHandler(createLeaveType));
hrRouter.patch('/leave/types/:id', authorizeHrModule('leave', 'manage'), asyncHandler(updateLeaveType));
hrRouter.delete('/leave/types/:id', authorizeHrModule('leave', 'manage'), asyncHandler(deleteLeaveType));
hrRouter.get('/leave/balances', authorizeHrModule('leave', 'view'), asyncHandler(listLeaveBalances));
hrRouter.get('/leave/requests', authorizeHrModule('leave', 'view'), asyncHandler(listLeaveRequests));
hrRouter.post('/leave/requests', authorizeHrModule('leave', 'view'), asyncHandler(createLeaveRequest));
hrRouter.patch('/leave/requests/:id', authorizeHrModule('leave', 'manage'), asyncHandler(decideLeaveRequest));
hrRouter.post('/leave/comp-off', authorizeHrModule('leave', 'manage'), asyncHandler(creditCompOff));
hrRouter.post('/leave/encashments', authorizeHrModule('leave', 'manage'), asyncHandler(encashLeave));
hrRouter.get('/expenses', authorizeHrModule('expenses', 'view'), asyncHandler(listExpenseClaims));
hrRouter.get('/expenses/employees', authorizeHrModule('expenses', 'manage'), asyncHandler(listEmployees));
hrRouter.post('/expenses', authorizeHrModule('expenses', 'view'), asyncHandler(createExpenseClaim));
hrRouter.patch('/expenses/:id', authorizeHrModule('expenses', 'manage'), asyncHandler(decideExpenseClaim));
hrRouter.get('/payroll/salary-structures', authorizeHrModule('payroll', 'manage'), asyncHandler(listSalaryStructures));
hrRouter.get('/payroll/employees', authorizeHrModule('payroll', 'manage'), asyncHandler(listEmployees));
hrRouter.post('/payroll/salary-structures', authorizeHrModule('payroll', 'manage'), asyncHandler(createSalaryStructure));
hrRouter.patch('/payroll/salary-structures/:id', authorizeHrModule('payroll', 'manage'), asyncHandler(updateSalaryStructure));
hrRouter.get('/advances', authorizeHrModule('payroll', 'view'), asyncHandler(listMyAdvances));
hrRouter.post('/advances', authorizeHrModule('payroll', 'view'), asyncHandler(requestAdvance));
hrRouter.get('/payroll/advances', authorizeHrModule('payroll', 'manage'), asyncHandler(listAdvances));
hrRouter.post('/payroll/advances', authorizeHrModule('payroll', 'manage'), asyncHandler(createAdvance));
hrRouter.patch('/payroll/advances/:id', authorizeHrModule('payroll', 'manage'), asyncHandler(decideAdvance));
hrRouter.post('/payroll/preview', authorizeHrModule('payroll', 'manage'), asyncHandler(previewPayroll));
hrRouter.get('/payroll/runs', authorizeHrModule('payroll', 'manage'), asyncHandler(listPayrollRuns));
hrRouter.post('/payroll/runs', authorizeHrModule('payroll', 'manage'), asyncHandler(createPayrollRun));
hrRouter.get('/payroll/runs/:id', authorizeHrModule('payroll', 'manage'), asyncHandler(getPayrollRun));
hrRouter.post('/payroll/runs/:id/process', authorizeHrModule('payroll', 'manage'), asyncHandler(processPayrollRun));
hrRouter.get('/payroll/runs/:id/bank-file', authorizeHrModule('payroll', 'manage'), asyncHandler(downloadBankFile));
hrRouter.get('/payroll/settlements/:employeeId', authorizeHrModule('payroll', 'manage'), asyncHandler(previewSettlement));
hrRouter.get('/reports/attendance-leave', authorizeHrModule('reports', 'view'), asyncHandler(attendanceLeaveReport));
hrRouter.get('/reports/payroll-cost', authorizeHrModule('reports', 'view'), asyncHandler(payrollCostReport));
hrRouter.get('/reports/headcount-attrition', authorizeHrModule('reports', 'view'), asyncHandler(headcountAttritionReport));
