import PageMetaData from '@/components/PageTitle'
import { apiFetch } from '@/helpers/api'
import { useEffect, useMemo, useState } from 'react'
import { Alert, Button, Card, CardBody, Col, Form, Row, Table } from 'react-bootstrap'
type Purchase = { _id: string; quantity: number; purchaseDate: string; reference?: string; note?: string; bill?: { originalName: string; url?: string }; item?: { name: string; sku: string; unit: string; supplier?: { name: string; contactPerson?: string; phone?: string } } }
export default function PurchasesPage() {
  const [items, setItems] = useState<Purchase[]>([]); const [error, setError] = useState(''); const [supplier, setSupplier] = useState(''); const [material, setMaterial] = useState(''); const [bill, setBill] = useState('all')
  useEffect(() => { apiFetch<{ data: Purchase[] }>('/inventory/purchases').then((response) => setItems(response.data)).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load purchases')) }, [])
  const suppliers = [...new Set(items.map((entry) => entry.item?.supplier?.name).filter(Boolean))].sort()
  const materials = [...new Set(items.map((entry) => entry.item?.name).filter(Boolean))].sort()
  const visible = useMemo(() => items.filter((entry) => (!supplier || entry.item?.supplier?.name === supplier) && (!material || entry.item?.name === material) && (bill === 'all' || bill === 'attached' ? Boolean(entry.bill) : !entry.bill)), [items, supplier, material, bill])
  return <><PageMetaData title="Purchase History" /><h4 className="mb-3">Purchase History</h4>{error && <Alert variant="danger">{error}</Alert>}<Card><CardBody><Row className="g-2 mb-3"><Col md={4}><Form.Select value={supplier} onChange={(event) => setSupplier(event.target.value)}><option value="">All suppliers</option>{suppliers.map((name) => <option key={name}>{name}</option>)}</Form.Select></Col><Col md={4}><Form.Select value={material} onChange={(event) => setMaterial(event.target.value)}><option value="">All materials</option>{materials.map((name) => <option key={name}>{name}</option>)}</Form.Select></Col><Col md={2}><Form.Select value={bill} onChange={(event) => setBill(event.target.value)}><option value="all">All bills</option><option value="attached">Bill attached</option><option value="missing">No bill</option></Form.Select></Col><Col md={2}><Button className="w-100" variant="outline-secondary" onClick={() => { setSupplier(''); setMaterial(''); setBill('all') }}>Clear filters</Button></Col></Row><Table responsive hover><thead><tr><th>Purchase date</th><th>Material</th><th>Quantity</th><th>Supplier</th><th>Reference / Notes</th><th>Bill</th></tr></thead><tbody>{visible.map((entry) => <tr key={entry._id}><td>{new Date(entry.purchaseDate).toLocaleDateString()}</td><td>{entry.item?.name || '—'}<small className="d-block text-muted">{entry.item?.sku}</small></td><td>{entry.quantity} {entry.item?.unit}</td><td>{entry.item?.supplier?.name || 'No supplier'}<small className="d-block text-muted">{entry.item?.supplier?.contactPerson || entry.item?.supplier?.phone || ''}</small></td><td>{entry.reference || '—'}<small className="d-block text-muted">{entry.note || ''}</small></td><td>{entry.bill?.url ? <a href={entry.bill.url} target="_blank" rel="noreferrer">{entry.bill.originalName}</a> : '—'}</td></tr>)}{!visible.length && <tr><td colSpan={6} className="text-center text-muted py-4">No purchases match these filters.</td></tr>}</tbody></Table></CardBody></Card></>
}
