import PageMetaData from '@/components/PageTitle'
import { apiFetch } from '@/helpers/api'
import type { EmployeeType } from '@/types/hr'
import { FormEvent, useEffect, useState } from 'react'
import { Alert, Button, Card, CardBody, Form, Table } from 'react-bootstrap'

type Advance = { _id: string; employee: EmployeeType; amount: number; deductedAmount: number; reason: string; status: string; deductionSchedule: { monthlyAmount: number } }
const AdvancesPage = () => {
  const [employees, setEmployees] = useState<EmployeeType[]>([]); const [advances, setAdvances] = useState<Advance[]>([]); const [form, setForm] = useState({ employee: '', amount: '', reason: '', monthlyAmount: '' }); const [error, setError] = useState('')
  const load = () => Promise.all([apiFetch<{ data: EmployeeType[] }>('/hr/payroll/employees?limit=100'), apiFetch<{ data: Advance[] }>('/hr/payroll/advances')]).then(([employeeResponse, advanceResponse]) => { setEmployees(employeeResponse.data); setAdvances(advanceResponse.data) }).catch((value) => setError(value instanceof Error ? value.message : 'Unable to load advances'))
  useEffect(() => { load() }, [])
  const create = async (event: FormEvent) => { event.preventDefault(); try { await apiFetch('/hr/payroll/advances', { method: 'POST', body: JSON.stringify({ employee: form.employee, amount: Number(form.amount), reason: form.reason, deductionSchedule: { monthlyAmount: Number(form.monthlyAmount) } }) }); setForm({ employee: '', amount: '', reason: '', monthlyAmount: '' }); load() } catch (value) { setError(value instanceof Error ? value.message : 'Unable to create advance') } }
  const decide = async (id: string, status: 'approved' | 'rejected') => { try { await apiFetch(`/hr/payroll/advances/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); load() } catch (value) { setError(value instanceof Error ? value.message : 'Unable to update advance') } }
  return <><PageMetaData title="Advances" /><Card><CardBody><h4 className="card-title mb-3">Employee advances</h4>{error && <Alert variant="danger">{error}</Alert>}<Form className="row g-2 mb-4" onSubmit={create}><div className="col-md-3"><Form.Select required value={form.employee} onChange={(event) => setForm({ ...form, employee: event.target.value })}><option value="">Employee</option>{employees.map((employee) => <option key={employee._id} value={employee._id}>{employee.user.name}</option>)}</Form.Select></div><div className="col-md-2"><Form.Control required min="1" type="number" placeholder="Amount" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></div><div className="col-md-3"><Form.Control required placeholder="Reason" value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></div><div className="col-md-2"><Form.Control required min="1" type="number" placeholder="Monthly deduction" value={form.monthlyAmount} onChange={(event) => setForm({ ...form, monthlyAmount: event.target.value })} /></div><div className="col-md-2"><Button type="submit">Request</Button></div></Form><Table responsive><thead><tr><th>Employee</th><th>Amount</th><th>Deducted</th><th>Monthly</th><th>Status</th><th /></tr></thead><tbody>{advances.map((advance) => <tr key={advance._id}><td>{advance.employee?.user?.name}</td><td>{advance.amount}</td><td>{advance.deductedAmount}</td><td>{advance.deductionSchedule.monthlyAmount}</td><td>{advance.status}</td><td>{advance.status === 'pending' && <><Button size="sm" className="me-2" onClick={() => decide(advance._id, 'approved')}>Approve</Button><Button size="sm" variant="outline-danger" onClick={() => decide(advance._id, 'rejected')}>Reject</Button></>}</td></tr>)}</tbody></Table></CardBody></Card></>
}
export default AdvancesPage
