export function htmlEscape(value) {
  return String(value || '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
}

export function dashboardUrl() {
  const configuredUrl = process.env.APP_URL || String(process.env.CORS_ORIGIN || '').split(',')[0];
  return /^https?:\/\//i.test(configuredUrl) ? configuredUrl.replace(/\/$/, '') : 'http://localhost:5173';
}

export function detailRows(items) {
  return items.map(([label, value], index) => `<tr><td style="padding:7px 0;font-size:13px;color:#6b7280;width:140px;${index === items.length - 1 ? '' : 'border-bottom:1px solid #edeef1;'}">${htmlEscape(label)}</td><td style="padding:7px 0;font-size:14px;color:#111827;font-weight:600;${index === items.length - 1 ? '' : 'border-bottom:1px solid #edeef1;'}">${htmlEscape(value || '-')}</td></tr>`).join('');
}

export function notificationLayout({ module, badge, badgeColor = '#eaf1fb', badgeText = '#0f1f3d', heading, intro, summary, details, actionLabel, actionUrl }) {
  return `<!doctype html><html><body style="margin:0;padding:0;background:#eef0f3;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef0f3;padding:40px 0"><tr><td align="center"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="max-width:600px;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(15,31,61,.08)"><tr><td style="background:#000;padding:28px 36px"><table role="presentation" width="100%"><tr><td><img src="https://absteras.com/images/logo/logo.png" alt="Absteras" height="30" style="display:block"></td><td align="right" style="font-size:12px;color:#c9a227;letter-spacing:1px;text-transform:uppercase;font-weight:700">${htmlEscape(module)}</td></tr></table></td></tr><tr><td style="background:#c9a227;height:3px;font-size:0">&nbsp;</td></tr><tr><td style="padding:36px 36px 0"><span style="display:inline-block;background:${badgeColor};color:${badgeText};font-size:11px;font-weight:700;letter-spacing:.8px;text-transform:uppercase;padding:6px 14px;border-radius:20px">${htmlEscape(badge)}</span></td></tr><tr><td style="padding:18px 36px 0"><h1 style="margin:0 0 10px;font-size:21px;color:#0f1f3d">${htmlEscape(heading)}</h1><p style="margin:0 0 22px;font-size:15px;line-height:1.7;color:#4b5563">${intro}</p></td></tr><tr><td style="padding:0 36px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f8f9fb;border:1px solid #e5e7eb;border-radius:8px"><tr><td style="padding:22px 26px">${summary || ''}<table role="presentation" width="100%" cellspacing="0" cellpadding="0">${details}</table></td></tr></table></td></tr><tr><td align="center" style="padding:30px 36px 10px"><a href="${htmlEscape(actionUrl)}" target="_blank" style="display:inline-block;padding:13px 30px;background:#0f1f3d;color:#fff;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600">${htmlEscape(actionLabel)}</a></td></tr><tr><td style="padding:28px 36px 32px;border-top:1px solid #e5e7eb"><p style="margin:20px 0 4px;font-size:13px;color:#6b7280;font-weight:700">Absteras</p><p style="margin:0 0 14px;font-size:12px;line-height:1.6;color:#9ca3af">This is an automated notification from the Absteras ${htmlEscape(module)} System. Please do not reply directly to this email.</p><p style="margin:0;font-size:11px;color:#c1c5cc">&copy; ${new Date().getFullYear()} Absteras. All rights reserved.</p></td></tr></table></td></tr></table></body></html>`;
}
