import { renderPdf } from '../../../services/pdf.service.js';

const escape = (value) => String(value ?? '-').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
const money = (value) => Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function createInvoicePdf(invoice) {
  const client = invoice.client; const items = invoice.lineItems.map((item, index) => `<tr><td>${index + 1}</td><td>${escape(item.description)}</td><td>${escape(item.hsnCode)}</td><td class="right">${item.quantity} ${escape(item.unit)}</td><td class="right">${money(item.unitPrice)}</td><td class="right">${money(item.lineAmount)}</td></tr>`).join('');
  const tax = [['IGST', invoice.igstAmount], ['CGST', invoice.cgstAmount], ['SGST', invoice.sgstAmount]].filter(([, value]) => value).map(([label, value]) => `<tr><td colspan="5" class="right">${label}</td><td class="right">${money(value)}</td></tr>`).join('');
  return renderPdf(`<!doctype html><html><head><style>@page{size:A4;margin:12mm}body{font:11px Arial;color:#000}.top,.items{width:100%;border-collapse:collapse}.top td{padding:6px;border-bottom:1px solid;font-weight:bold}.center{text-align:center}.right{text-align:right}.items td,.items th{border:1px solid;padding:6px}.company{text-align:center;border-bottom:1px solid;padding:12px}.parties{display:flex;margin-top:12px}.parties>div{width:50%;border:1px solid;padding:8px;min-height:100px}.meta{display:flex;border-bottom:1px solid}.meta>div{width:50%;padding:8px}.terms{margin-top:18px}.sign{text-align:right;font-weight:bold;margin-top:35px}</style></head><body><table class="top"><tr><td>GSTIN: 06ABXFA0801H1ZK</td><td class="center">TAX INVOICE</td><td class="right">ORIGINAL COPY</td></tr></table><div class="company"><h1>ABSTERAS</h1><div>LOWER GROUND, PLOT NO 1140, BLOCK A, SUSHANT LOK-1, GURUGRAM, HARYANA</div></div><div class="meta"><div><b>Invoice No.:</b> ${escape(invoice.invoiceNumber)}<br><b>Date:</b> ${new Date(invoice.invoiceDate).toLocaleDateString('en-GB')}<br><b>Place of Supply:</b> ${escape(invoice.placeOfSupply)} (${escape(invoice.placeOfSupplyCode)})<br><b>Reverse Charge:</b> ${invoice.reverseCharge ? 'Yes' : 'No'}</div><div><b>GR/RR No.:</b> ${escape(invoice.grRrNumber)}<br><b>Transport:</b> ${escape(invoice.transport)}<br><b>Vehicle No.:</b> ${escape(invoice.vehicleNumber)}<br><b>Station:</b> ${escape(invoice.station)}</div></div><div class="parties"><div><b>Billed to:</b><br><br><b>${escape(client.name)}</b><br>${escape(client.billingAddress)}<br><br>GSTIN / UIN: ${escape(client.gstin)}</div><div><b>Shipped to:</b><br><br><b>${escape(client.name)}</b><br>${escape(client.shippingAddress || client.billingAddress)}<br><br>GSTIN / UIN: ${escape(client.gstin)}</div></div><table class="items"><thead><tr><th>#</th><th>Description of Goods</th><th>HSN/SAC</th><th>Qty.</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>${items}</tbody><tfoot><tr><td colspan="5" class="right">Taxable Amount</td><td class="right">${money(invoice.taxableAmount)}</td></tr>${tax}${invoice.roundOff ? `<tr><td colspan="5" class="right">Round Off</td><td class="right">${money(invoice.roundOff)}</td></tr>` : ''}<tr><th colspan="5" class="right">Grand Total</th><th class="right">${money(invoice.grandTotal)}</th></tr></tfoot></table><div class="terms"><b>Terms & Conditions</b><br>Goods once sold will not be taken back. Interest at 18% p.a. applies to overdue payments. Subject to Haryana jurisdiction.</div><div class="sign">For ABSTERAS<br><br>Authorised Signatory</div></body></html>`);
}
