import { Form } from 'react-bootstrap'

export type Client = { _id: string; name: string; gstin?: string; billingAddress?: string; shippingAddress?: string; state?: string; stateCode?: string; phone?: string; email?: string; siteName?: string; siteAddress?: string; startDate?: string; status: 'active' | 'on hold' | 'completed'; estimatedValue?: number; notes?: string }
export type ClientInput = Omit<Client, '_id' | 'estimatedValue'> & { estimatedValue: string }

export const emptyClientInput: ClientInput = { name: '', gstin: '', billingAddress: '', shippingAddress: '', state: '', stateCode: '', phone: '', email: '', siteName: '', siteAddress: '', startDate: '', status: 'active', estimatedValue: '', notes: '' }
export const inputFromClient = (client: Client): ClientInput => ({ ...emptyClientInput, ...client, startDate: client.startDate?.slice(0, 10) || '', estimatedValue: client.estimatedValue?.toString() || '' })
export const clientPayload = (input: ClientInput) => ({ ...input, estimatedValue: input.estimatedValue === '' ? undefined : Number(input.estimatedValue), startDate: input.startDate || undefined })

export const ClientFields = ({ value, onChange }: { value: ClientInput; onChange: (value: ClientInput) => void }) => {
  const set = <K extends keyof ClientInput>(key: K, next: ClientInput[K]) => onChange({ ...value, [key]: next })
  return <div className="row g-3"><div className="col-md-6"><Form.Label>Client name</Form.Label><Form.Control required value={value.name} onChange={(event) => set('name', event.target.value)} /></div><div className="col-md-6"><Form.Label>Site / project name</Form.Label><Form.Control value={value.siteName || ''} onChange={(event) => set('siteName', event.target.value)} /></div><div className="col-md-6"><Form.Label>Phone</Form.Label><Form.Control value={value.phone || ''} onChange={(event) => set('phone', event.target.value)} /></div><div className="col-md-6"><Form.Label>Email</Form.Label><Form.Control type="email" value={value.email || ''} onChange={(event) => set('email', event.target.value)} /></div><div className="col-md-8"><Form.Label>GSTIN</Form.Label><Form.Control value={value.gstin || ''} onChange={(event) => set('gstin', event.target.value)} /></div><div className="col-md-4"><Form.Label>Status</Form.Label><Form.Select value={value.status} onChange={(event) => set('status', event.target.value as Client['status'])}>{['active', 'on hold', 'completed'].map((status) => <option key={status}>{status}</option>)}</Form.Select></div><div className="col-md-8"><Form.Label>State</Form.Label><Form.Control value={value.state || ''} onChange={(event) => set('state', event.target.value)} /></div><div className="col-md-4"><Form.Label>State code</Form.Label><Form.Control inputMode="numeric" pattern="[0-9]{2}" maxLength={2} value={value.stateCode || ''} onChange={(event) => set('stateCode', event.target.value)} /></div><div className="col-md-4"><Form.Label>Billing address</Form.Label><Form.Control as="textarea" rows={2} value={value.billingAddress || ''} onChange={(event) => set('billingAddress', event.target.value)} /></div><div className="col-md-4"><Form.Label>Shipping address</Form.Label><Form.Control as="textarea" rows={2} value={value.shippingAddress || ''} onChange={(event) => set('shippingAddress', event.target.value)} /></div><div className="col-md-4"><Form.Label>Site address</Form.Label><Form.Control as="textarea" rows={2} value={value.siteAddress || ''} onChange={(event) => set('siteAddress', event.target.value)} /></div><div className="col-md-6"><Form.Label>Start date</Form.Label><Form.Control type="date" value={value.startDate || ''} onChange={(event) => set('startDate', event.target.value)} /></div><div className="col-md-6"><Form.Label>Estimated value</Form.Label><Form.Control type="number" min="0" value={value.estimatedValue} onChange={(event) => set('estimatedValue', event.target.value)} /></div><div className="col-12"><Form.Label>Notes</Form.Label><Form.Control as="textarea" rows={2} value={value.notes || ''} onChange={(event) => set('notes', event.target.value)} /></div></div>
}
