import { Router } from 'express';
import { uploadFiles } from '../../controllers/upload.controller.js';
import { asyncHandler } from '../../middleware/async-handler.js';
import { multipartUpload } from '../../middleware/upload.middleware.js';
import { rateLimit } from '../../middleware/rate-limit.middleware.js';
import { authenticate, authorizeAppModule, authorizeDesignerDirector } from '../auth/middleware/auth.middleware.js';
import * as controller from './designer.controller.js';
import * as drawing from './drawing.controller.js';
import * as productionData from './production-data.controller.js';
import * as siteMeasurement from './site-measurement.controller.js';

export const designerRouter = Router();
designerRouter.use(asyncHandler(authenticate), authorizeAppModule('designer'));
designerRouter.get('/client-sites', asyncHandler(controller.listClientSites));
designerRouter.get('/boqs', asyncHandler(controller.listBoqs));
designerRouter.get('/boqs/:id', asyncHandler(controller.getBoq));
designerRouter.get('/drawings', asyncHandler(drawing.listDrawings));
designerRouter.get('/drawings/:id', asyncHandler(drawing.getDrawing));
designerRouter.get('/site-measurements', asyncHandler(siteMeasurement.listSiteMeasurements));
designerRouter.get('/production-data/eligibility', authorizeAppModule('designer', 'manage'), asyncHandler(productionData.getProductionDataEligibility));
designerRouter.get('/production-data', asyncHandler(productionData.listProductionData));
designerRouter.post('/uploads', authorizeAppModule('designer', 'manage'), asyncHandler(rateLimit({ scope: 'designer-upload', limit: 10, windowMs: 15 * 60 * 1000 })), multipartUpload, asyncHandler(uploadFiles));
designerRouter.post('/boqs', authorizeAppModule('designer', 'manage'), asyncHandler(controller.createBoq));
designerRouter.post('/boqs/:id/resubmit', authorizeAppModule('designer', 'manage'), asyncHandler(controller.resubmitBoq));
designerRouter.post('/boqs/:id/review', authorizeDesignerDirector, asyncHandler(controller.reviewBoq));
designerRouter.post('/drawings', authorizeAppModule('designer', 'manage'), asyncHandler(drawing.createDrawing));
designerRouter.post('/drawings/:id/resubmit', authorizeAppModule('designer', 'manage'), asyncHandler(drawing.resubmitDrawing));
designerRouter.post('/drawings/:id/review', authorizeDesignerDirector, asyncHandler(drawing.reviewDrawing));
designerRouter.post('/site-measurements', authorizeAppModule('designer', 'manage'), asyncHandler(siteMeasurement.createSiteMeasurement));
designerRouter.post('/production-data', authorizeAppModule('designer', 'manage'), asyncHandler(productionData.createProductionData));
