import { renderPdf } from '../../../services/pdf.service.js';

const escape = (value) => String(value ?? '-').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
const money = (value) => `AED ${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const row = (label, amount) => `<tr><td>${escape(label)}</td><td class="right">${money(amount)}</td></tr>`;

export function createPayslipPdf({ employee, entry, salary, month, year }) {
  const allowances = (salary?.allowances || []).map((allowance) => row(allowance.name, allowance.amount)).join('');
  return renderPdf(`<!doctype html><html><head><style>@page{size:A4;margin:15mm}body{font:11px Arial;color:#111;border:2px solid #111;padding:18px}h1,h2{margin:0;text-align:center}.muted{text-align:center;color:#555;margin:5px 0 22px}.info{width:100%;margin:15px 0;border-collapse:collapse}.info td{width:50%;padding:4px}.table{width:100%;border-collapse:collapse;margin-top:12px}.table th,.table td{border-bottom:1px solid #bbb;padding:7px}.right{text-align:right}.total{font-weight:bold}.footer{text-align:center;color:#555;margin-top:35px;font-size:9px}</style></head><body><h1>PAYSLIP</h1><h2>ABSTERAS COMPANY CRM</h2><div class="muted">System generated salary slip</div><table class="info"><tr><td>Employee Name: <b>${escape(employee.user?.name)}</b></td><td>Pay Period: <b>${new Date(Date.UTC(year, month - 1, 1)).toLocaleString('en-US', { month: 'long', year: 'numeric' })}</b></td></tr><tr><td>Designation: <b>${escape(employee.designation?.name)}</b></td><td>Department: <b>${escape(employee.department?.name)}</b></td></tr><tr><td>Date of Joining: <b>${employee.joiningDate ? new Date(employee.joiningDate).toLocaleDateString('en-CA') : '-'}</b></td><td>Worked Days: <b>${escape(entry.payableDays)}</b></td></tr></table><table class="table"><thead><tr><th>Earnings</th><th class="right">Amount</th></tr></thead><tbody>${row('Basic salary', salary?.basic)}${row('House rent allowance', salary?.hra)}${allowances}${entry.reimbursementPay ? row('Reimbursements', entry.reimbursementPay) : ''}${entry.encashmentPay ? row('Leave encashment', entry.encashmentPay) : ''}${row('Total earnings', entry.grossPay)}</tbody></table><table class="table"><thead><tr><th>Deductions</th><th class="right">Amount</th></tr></thead><tbody>${entry.unpaidDeduction ? row('Unpaid leave / absence', entry.unpaidDeduction) : ''}${entry.advanceDeducted ? row('Salary advance', entry.advanceDeducted) : ''}${!entry.unpaidDeduction && !entry.advanceDeducted ? row('No deductions', 0) : ''}${row('Total deductions', entry.deductions)}</tbody></table><table class="table total"><tr><td>Net Pay</td><td class="right">${money(entry.netPay)}</td></tr></table><div class="footer">This is a system generated payslip.</div></body></html>`);
}
