import { Router } from 'express';
import { addTaskNote, createTask, createTaskWorkType, deleteTask, deleteTaskWorkType, getTask, handoffTask, listTaskAssignees, listTaskWorkTypes, listTasks, updateTask } from './controllers/task.controller.js';
import { deleteUpload, uploadFiles } from '../../controllers/upload.controller.js';
import { asyncHandler } from '../../middleware/async-handler.js';
import { multipartUpload } from '../../middleware/upload.middleware.js';
import { rateLimit } from '../../middleware/rate-limit.middleware.js';
import { authenticate, authorizeAppModule } from '../auth/middleware/auth.middleware.js';

export const taskRouter = Router();
taskRouter.use(asyncHandler(authenticate), authorizeAppModule('tasks'));
taskRouter.get('/', asyncHandler(listTasks));
taskRouter.get('/assignees', asyncHandler(listTaskAssignees));
taskRouter.get('/work-types', asyncHandler(listTaskWorkTypes));
taskRouter.post('/uploads', authorizeAppModule('tasks', 'manage'), asyncHandler(rateLimit({ scope: 'task-upload', limit: 10, windowMs: 15 * 60 * 1000 })), multipartUpload, asyncHandler(uploadFiles));
taskRouter.delete('/uploads', authorizeAppModule('tasks', 'manage'), asyncHandler(rateLimit({ scope: 'task-upload-remove', limit: 30, windowMs: 15 * 60 * 1000 })), asyncHandler(deleteUpload));
taskRouter.post('/work-types', authorizeAppModule('tasks', 'manage'), asyncHandler(createTaskWorkType));
taskRouter.delete('/work-types/:role/:name', authorizeAppModule('tasks', 'manage'), asyncHandler(deleteTaskWorkType));
taskRouter.post('/', authorizeAppModule('tasks', 'manage'), asyncHandler(createTask));
taskRouter.get('/:id', asyncHandler(getTask));
taskRouter.patch('/:id', asyncHandler(updateTask));
taskRouter.post('/:id/handoff', asyncHandler(handoffTask));
taskRouter.post('/:id/notes', asyncHandler(addTaskNote));
taskRouter.delete('/:id', authorizeAppModule('tasks', 'manage'), asyncHandler(deleteTask));
